- name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true # This will give us more details if it fails
          script: |
            cd /var/www/AI-VIRALCLIPS
            git pull origin main
            
            # Create the .env file
            echo "${{ secrets.PROD_ENV_FILE }}" > app/.env
            
            # Setup Backend
            python3.12 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            
            # Frontend permissions
            chmod -R 755 frontend